// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: api_keys.sql

package dbgen

import (
	"context"
	"time"
)

const createAPIKey = `-- name: CreateAPIKey :one
INSERT INTO api_keys (user_id, key_hash, prefix, name)
VALUES ($1, $2, $3, $4)
RETURNING id, user_id, prefix, name, created_at, last_used_at, revoked_at
`

type CreateAPIKeyParams struct {
	UserID  int64
	KeyHash []byte
	Prefix  string
	Name    string
}

type CreateAPIKeyRow struct {
	ID         int64
	UserID     int64
	Prefix     string
	Name       string
	CreatedAt  time.Time
	LastUsedAt *time.Time
	RevokedAt  *time.Time
}

func (q *Queries) CreateAPIKey(ctx context.Context, arg CreateAPIKeyParams) (CreateAPIKeyRow, error) {
	row := q.db.QueryRow(ctx, createAPIKey,
		arg.UserID,
		arg.KeyHash,
		arg.Prefix,
		arg.Name,
	)
	var i CreateAPIKeyRow
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Prefix,
		&i.Name,
		&i.CreatedAt,
		&i.LastUsedAt,
		&i.RevokedAt,
	)
	return i, err
}

const getUserByAPIKeyHash = `-- name: GetUserByAPIKeyHash :one
SELECT users.id, users.username, users.email, users.role, users.registered_at, api_keys.id AS api_key_id
FROM api_keys
JOIN users ON users.id = api_keys.user_id
WHERE api_keys.key_hash = $1 AND api_keys.revoked_at IS NULL
`

type GetUserByAPIKeyHashRow struct {
	User     User
	ApiKeyID int64
}

// Resolves an active (not revoked) key to its owner.
func (q *Queries) GetUserByAPIKeyHash(ctx context.Context, keyHash []byte) (GetUserByAPIKeyHashRow, error) {
	row := q.db.QueryRow(ctx, getUserByAPIKeyHash, keyHash)
	var i GetUserByAPIKeyHashRow
	err := row.Scan(
		&i.User.ID,
		&i.User.Username,
		&i.User.Email,
		&i.User.Role,
		&i.User.RegisteredAt,
		&i.ApiKeyID,
	)
	return i, err
}

const listAPIKeysByUser = `-- name: ListAPIKeysByUser :many
SELECT id, user_id, prefix, name, created_at, last_used_at, revoked_at
FROM api_keys
WHERE user_id = $1
ORDER BY id
`

type ListAPIKeysByUserRow struct {
	ID         int64
	UserID     int64
	Prefix     string
	Name       string
	CreatedAt  time.Time
	LastUsedAt *time.Time
	RevokedAt  *time.Time
}

// Never returns key_hash.
func (q *Queries) ListAPIKeysByUser(ctx context.Context, userID int64) ([]ListAPIKeysByUserRow, error) {
	rows, err := q.db.Query(ctx, listAPIKeysByUser, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListAPIKeysByUserRow
	for rows.Next() {
		var i ListAPIKeysByUserRow
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.Prefix,
			&i.Name,
			&i.CreatedAt,
			&i.LastUsedAt,
			&i.RevokedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const revokeAPIKey = `-- name: RevokeAPIKey :execrows
UPDATE api_keys SET revoked_at = now()
WHERE id = $1 AND user_id = $2 AND revoked_at IS NULL
`

type RevokeAPIKeyParams struct {
	ID     int64
	UserID int64
}

// Scoped by user_id so one user cannot revoke another user's key.
func (q *Queries) RevokeAPIKey(ctx context.Context, arg RevokeAPIKeyParams) (int64, error) {
	result, err := q.db.Exec(ctx, revokeAPIKey, arg.ID, arg.UserID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const touchAPIKey = `-- name: TouchAPIKey :exec
UPDATE api_keys SET last_used_at = now() WHERE id = $1
`

func (q *Queries) TouchAPIKey(ctx context.Context, id int64) error {
	_, err := q.db.Exec(ctx, touchAPIKey, id)
	return err
}
