// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: audio.sql

package dbgen

import (
	"context"
	"time"
)

const clearAudioStorageKey = `-- name: ClearAudioStorageKey :execrows
UPDATE audio SET storage_key = NULL WHERE source_id = $1 AND format = $2
`

type ClearAudioStorageKeyParams struct {
	SourceID string
	Format   AudioFormat
}

// Marks the file as no longer stored (e.g. evicted); the row is kept.
func (q *Queries) ClearAudioStorageKey(ctx context.Context, arg ClearAudioStorageKeyParams) (int64, error) {
	result, err := q.db.Exec(ctx, clearAudioStorageKey, arg.SourceID, arg.Format)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const countAudio = `-- name: CountAudio :one
SELECT count(*) FROM audio
`

func (q *Queries) CountAudio(ctx context.Context) (int64, error) {
	row := q.db.QueryRow(ctx, countAudio)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const deleteAudio = `-- name: DeleteAudio :execrows
DELETE FROM audio WHERE source_id = $1 AND format = $2
`

type DeleteAudioParams struct {
	SourceID string
	Format   AudioFormat
}

func (q *Queries) DeleteAudio(ctx context.Context, arg DeleteAudioParams) (int64, error) {
	result, err := q.db.Exec(ctx, deleteAudio, arg.SourceID, arg.Format)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const getAudio = `-- name: GetAudio :one
SELECT id, source_id, format, url, title, duration_seconds, storage_key, last_uploaded_at, created_at, last_requested_at FROM audio WHERE source_id = $1 AND format = $2
`

type GetAudioParams struct {
	SourceID string
	Format   AudioFormat
}

func (q *Queries) GetAudio(ctx context.Context, arg GetAudioParams) (Audio, error) {
	row := q.db.QueryRow(ctx, getAudio, arg.SourceID, arg.Format)
	var i Audio
	err := row.Scan(
		&i.ID,
		&i.SourceID,
		&i.Format,
		&i.Url,
		&i.Title,
		&i.DurationSeconds,
		&i.StorageKey,
		&i.LastUploadedAt,
		&i.CreatedAt,
		&i.LastRequestedAt,
	)
	return i, err
}

const getAudioByURL = `-- name: GetAudioByURL :one
SELECT id, source_id, format, url, title, duration_seconds, storage_key, last_uploaded_at, created_at, last_requested_at FROM audio WHERE url = $1 AND format = $2 ORDER BY last_requested_at DESC LIMIT 1
`

type GetAudioByURLParams struct {
	Url    string
	Format AudioFormat
}

func (q *Queries) GetAudioByURL(ctx context.Context, arg GetAudioByURLParams) (Audio, error) {
	row := q.db.QueryRow(ctx, getAudioByURL, arg.Url, arg.Format)
	var i Audio
	err := row.Scan(
		&i.ID,
		&i.SourceID,
		&i.Format,
		&i.Url,
		&i.Title,
		&i.DurationSeconds,
		&i.StorageKey,
		&i.LastUploadedAt,
		&i.CreatedAt,
		&i.LastRequestedAt,
	)
	return i, err
}

const listAudio = `-- name: ListAudio :many
SELECT id, source_id, format, url, title, duration_seconds, storage_key, last_uploaded_at, created_at, last_requested_at FROM audio
ORDER BY last_uploaded_at DESC, id DESC
LIMIT $1 OFFSET $2
`

type ListAudioParams struct {
	Limit  int32
	Offset int32
}

func (q *Queries) ListAudio(ctx context.Context, arg ListAudioParams) ([]Audio, error) {
	rows, err := q.db.Query(ctx, listAudio, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Audio
	for rows.Next() {
		var i Audio
		if err := rows.Scan(
			&i.ID,
			&i.SourceID,
			&i.Format,
			&i.Url,
			&i.Title,
			&i.DurationSeconds,
			&i.StorageKey,
			&i.LastUploadedAt,
			&i.CreatedAt,
			&i.LastRequestedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listIdleAudio = `-- name: ListIdleAudio :many
SELECT id, source_id, format, url, title, duration_seconds, storage_key, last_uploaded_at, created_at, last_requested_at FROM audio a
WHERE a.storage_key IS NOT NULL
  AND a.last_requested_at < $1::timestamptz
  AND NOT EXISTS (
      SELECT 1 FROM tasks t
      WHERE t.storage_key = a.storage_key
        AND (t.expires_at IS NULL OR t.expires_at > now())
        AND t.status IN ('queued', 'running', 'succeeded'))
ORDER BY a.last_requested_at
LIMIT $2
`

type ListIdleAudioParams struct {
	Cutoff    time.Time
	BatchSize int32
}

// Stored files not requested since the cutoff and not pinned by a task whose
// result is still downloadable.
func (q *Queries) ListIdleAudio(ctx context.Context, arg ListIdleAudioParams) ([]Audio, error) {
	rows, err := q.db.Query(ctx, listIdleAudio, arg.Cutoff, arg.BatchSize)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Audio
	for rows.Next() {
		var i Audio
		if err := rows.Scan(
			&i.ID,
			&i.SourceID,
			&i.Format,
			&i.Url,
			&i.Title,
			&i.DurationSeconds,
			&i.StorageKey,
			&i.LastUploadedAt,
			&i.CreatedAt,
			&i.LastRequestedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const touchAudioRequested = `-- name: TouchAudioRequested :execrows
UPDATE audio SET last_requested_at = now() WHERE source_id = $1 AND format = $2
`

type TouchAudioRequestedParams struct {
	SourceID string
	Format   AudioFormat
}

// Called whenever a stored file is served; keeps it from idle eviction.
func (q *Queries) TouchAudioRequested(ctx context.Context, arg TouchAudioRequestedParams) (int64, error) {
	result, err := q.db.Exec(ctx, touchAudioRequested, arg.SourceID, arg.Format)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const upsertAudio = `-- name: UpsertAudio :one
INSERT INTO audio (source_id, format, url, title, duration_seconds, storage_key)
VALUES ($1, $2, $3, $4, $5, $6)
ON CONFLICT (source_id, format) DO UPDATE
SET url              = EXCLUDED.url,
    title            = EXCLUDED.title,
    duration_seconds = EXCLUDED.duration_seconds,
    storage_key      = EXCLUDED.storage_key,
    last_uploaded_at = now(),
    last_requested_at = now()
RETURNING id, source_id, format, url, title, duration_seconds, storage_key, last_uploaded_at, created_at, last_requested_at
`

type UpsertAudioParams struct {
	SourceID        string
	Format          AudioFormat
	Url             string
	Title           string
	DurationSeconds *int32
	StorageKey      *string
}

// Records an upload to storage; a repeat upload of the same video in the same
// format refreshes the row and its last_uploaded_at.
func (q *Queries) UpsertAudio(ctx context.Context, arg UpsertAudioParams) (Audio, error) {
	row := q.db.QueryRow(ctx, upsertAudio,
		arg.SourceID,
		arg.Format,
		arg.Url,
		arg.Title,
		arg.DurationSeconds,
		arg.StorageKey,
	)
	var i Audio
	err := row.Scan(
		&i.ID,
		&i.SourceID,
		&i.Format,
		&i.Url,
		&i.Title,
		&i.DurationSeconds,
		&i.StorageKey,
		&i.LastUploadedAt,
		&i.CreatedAt,
		&i.LastRequestedAt,
	)
	return i, err
}
