// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: audio.sql

package dbgen

import (
	"context"
)

const clearAudioStorageKey = `-- name: ClearAudioStorageKey :execrows
UPDATE audio SET storage_key = NULL WHERE source_id = $1 AND format = $2
`

type ClearAudioStorageKeyParams struct {
	SourceID string
	Format   AudioFormat
}

// Marks the file as no longer stored (e.g. evicted); the row is kept.
func (q *Queries) ClearAudioStorageKey(ctx context.Context, arg ClearAudioStorageKeyParams) (int64, error) {
	result, err := q.db.Exec(ctx, clearAudioStorageKey, arg.SourceID, arg.Format)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const deleteAudio = `-- name: DeleteAudio :execrows
DELETE FROM audio WHERE source_id = $1 AND format = $2
`

type DeleteAudioParams struct {
	SourceID string
	Format   AudioFormat
}

func (q *Queries) DeleteAudio(ctx context.Context, arg DeleteAudioParams) (int64, error) {
	result, err := q.db.Exec(ctx, deleteAudio, arg.SourceID, arg.Format)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const getAudio = `-- name: GetAudio :one
SELECT id, source_id, format, url, title, duration_seconds, storage_key, last_uploaded_at, created_at FROM audio WHERE source_id = $1 AND format = $2
`

type GetAudioParams struct {
	SourceID string
	Format   AudioFormat
}

func (q *Queries) GetAudio(ctx context.Context, arg GetAudioParams) (Audio, error) {
	row := q.db.QueryRow(ctx, getAudio, arg.SourceID, arg.Format)
	var i Audio
	err := row.Scan(
		&i.ID,
		&i.SourceID,
		&i.Format,
		&i.Url,
		&i.Title,
		&i.DurationSeconds,
		&i.StorageKey,
		&i.LastUploadedAt,
		&i.CreatedAt,
	)
	return i, err
}

const listAudio = `-- name: ListAudio :many
SELECT id, source_id, format, url, title, duration_seconds, storage_key, last_uploaded_at, created_at FROM audio
ORDER BY last_uploaded_at DESC, id DESC
LIMIT $1 OFFSET $2
`

type ListAudioParams struct {
	Limit  int32
	Offset int32
}

func (q *Queries) ListAudio(ctx context.Context, arg ListAudioParams) ([]Audio, error) {
	rows, err := q.db.Query(ctx, listAudio, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Audio
	for rows.Next() {
		var i Audio
		if err := rows.Scan(
			&i.ID,
			&i.SourceID,
			&i.Format,
			&i.Url,
			&i.Title,
			&i.DurationSeconds,
			&i.StorageKey,
			&i.LastUploadedAt,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const upsertAudio = `-- name: UpsertAudio :one
INSERT INTO audio (source_id, format, url, title, duration_seconds, storage_key)
VALUES ($1, $2, $3, $4, $5, $6)
ON CONFLICT (source_id, format) DO UPDATE
SET url              = EXCLUDED.url,
    title            = EXCLUDED.title,
    duration_seconds = EXCLUDED.duration_seconds,
    storage_key      = EXCLUDED.storage_key,
    last_uploaded_at = now()
RETURNING id, source_id, format, url, title, duration_seconds, storage_key, last_uploaded_at, created_at
`

type UpsertAudioParams struct {
	SourceID        string
	Format          AudioFormat
	Url             string
	Title           string
	DurationSeconds *int32
	StorageKey      *string
}

// Records an upload to storage; a repeat upload of the same video in the same
// format refreshes the row and its last_uploaded_at.
func (q *Queries) UpsertAudio(ctx context.Context, arg UpsertAudioParams) (Audio, error) {
	row := q.db.QueryRow(ctx, upsertAudio,
		arg.SourceID,
		arg.Format,
		arg.Url,
		arg.Title,
		arg.DurationSeconds,
		arg.StorageKey,
	)
	var i Audio
	err := row.Scan(
		&i.ID,
		&i.SourceID,
		&i.Format,
		&i.Url,
		&i.Title,
		&i.DurationSeconds,
		&i.StorageKey,
		&i.LastUploadedAt,
		&i.CreatedAt,
	)
	return i, err
}
