// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: history.sql

package dbgen

import (
	"context"
	"time"

	"github.com/google/uuid"
)

const countHistory = `-- name: CountHistory :one
SELECT count(*) FROM request_history
WHERE ($1::bigint IS NULL OR user_id = $1)
  AND ($2::request_kind IS NULL OR kind = $2)
  AND ($3::request_status IS NULL OR status = $3)
  AND ($4::media_format IS NULL OR format = $4)
  AND ($5::timestamptz IS NULL OR created_at >= $5)
  AND ($6::timestamptz IS NULL OR created_at < $6)
  AND ($7::text IS NULL
       OR query ILIKE '%' || $7 || '%'
       OR source_url ILIKE '%' || $7 || '%'
       OR title ILIKE '%' || $7 || '%')
`

type CountHistoryParams struct {
	UserID      *int64
	Kind        NullRequestKind
	Status      NullRequestStatus
	Format      NullMediaFormat
	CreatedFrom *time.Time
	CreatedTo   *time.Time
	Search      *string
}

func (q *Queries) CountHistory(ctx context.Context, arg CountHistoryParams) (int64, error) {
	row := q.db.QueryRow(ctx, countHistory,
		arg.UserID,
		arg.Kind,
		arg.Status,
		arg.Format,
		arg.CreatedFrom,
		arg.CreatedTo,
		arg.Search,
	)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const finishHistory = `-- name: FinishHistory :exec
UPDATE request_history
SET status      = $1,
    http_status = $2,
    source_id   = coalesce($3, source_id),
    title       = coalesce(nullif($4::text, ''), title),
    from_cache  = $5,
    error       = $6,
    duration_ms = (extract(epoch FROM now() - created_at) * 1000)::bigint
WHERE id = $7
`

type FinishHistoryParams struct {
	Status     RequestStatus
	HttpStatus *int32
	SourceID   *string
	Title      string
	FromCache  bool
	Error      *string
	ID         int64
}

func (q *Queries) FinishHistory(ctx context.Context, arg FinishHistoryParams) error {
	_, err := q.db.Exec(ctx, finishHistory,
		arg.Status,
		arg.HttpStatus,
		arg.SourceID,
		arg.Title,
		arg.FromCache,
		arg.Error,
		arg.ID,
	)
	return err
}

const insertHistory = `-- name: InsertHistory :one
INSERT INTO request_history (user_id, api_key_id, kind, query, source_url, format, task_id)
VALUES ($1, $2, $3, $4, $5, $6, $7)
RETURNING id
`

type InsertHistoryParams struct {
	UserID    int64
	ApiKeyID  *int64
	Kind      RequestKind
	Query     string
	SourceUrl string
	Format    MediaFormat
	TaskID    *uuid.UUID
}

func (q *Queries) InsertHistory(ctx context.Context, arg InsertHistoryParams) (int64, error) {
	row := q.db.QueryRow(ctx, insertHistory,
		arg.UserID,
		arg.ApiKeyID,
		arg.Kind,
		arg.Query,
		arg.SourceUrl,
		arg.Format,
		arg.TaskID,
	)
	var id int64
	err := row.Scan(&id)
	return id, err
}

const listHistory = `-- name: ListHistory :many
SELECT id, user_id, api_key_id, kind, query, source_url, format, source_id, title, status, http_status, from_cache, task_id, error, duration_ms, created_at FROM request_history
WHERE ($1::bigint IS NULL OR user_id = $1)
  AND ($2::request_kind IS NULL OR kind = $2)
  AND ($3::request_status IS NULL OR status = $3)
  AND ($4::media_format IS NULL OR format = $4)
  AND ($5::timestamptz IS NULL OR created_at >= $5)
  AND ($6::timestamptz IS NULL OR created_at < $6)
  AND ($7::text IS NULL
       OR query ILIKE '%' || $7 || '%'
       OR source_url ILIKE '%' || $7 || '%'
       OR title ILIKE '%' || $7 || '%')
ORDER BY
  CASE WHEN $8::boolean THEN created_at END ASC,
  CASE WHEN $8::boolean THEN id END ASC,
  CASE WHEN NOT $8::boolean THEN created_at END DESC,
  CASE WHEN NOT $8::boolean THEN id END DESC
LIMIT $10 OFFSET $9
`

type ListHistoryParams struct {
	UserID      *int64
	Kind        NullRequestKind
	Status      NullRequestStatus
	Format      NullMediaFormat
	CreatedFrom *time.Time
	CreatedTo   *time.Time
	Search      *string
	SortAsc     bool
	PageOffset  int32
	PageLimit   int32
}

// Every filter is optional (NULL = no filter). search must already have its
// LIKE wildcards escaped by the caller.
func (q *Queries) ListHistory(ctx context.Context, arg ListHistoryParams) ([]RequestHistory, error) {
	rows, err := q.db.Query(ctx, listHistory,
		arg.UserID,
		arg.Kind,
		arg.Status,
		arg.Format,
		arg.CreatedFrom,
		arg.CreatedTo,
		arg.Search,
		arg.SortAsc,
		arg.PageOffset,
		arg.PageLimit,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []RequestHistory
	for rows.Next() {
		var i RequestHistory
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.ApiKeyID,
			&i.Kind,
			&i.Query,
			&i.SourceUrl,
			&i.Format,
			&i.SourceID,
			&i.Title,
			&i.Status,
			&i.HttpStatus,
			&i.FromCache,
			&i.TaskID,
			&i.Error,
			&i.DurationMs,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
