// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package dbgen

import (
	"database/sql/driver"
	"fmt"
	"time"

	"github.com/google/uuid"
)

type AudioFormat string

const (
	AudioFormatMp3 AudioFormat = "mp3"
	AudioFormatWav AudioFormat = "wav"
)

func (e *AudioFormat) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = AudioFormat(s)
	case string:
		*e = AudioFormat(s)
	default:
		return fmt.Errorf("unsupported scan type for AudioFormat: %T", src)
	}
	return nil
}

type NullAudioFormat struct {
	AudioFormat AudioFormat
	Valid       bool // Valid is true if AudioFormat is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullAudioFormat) Scan(value interface{}) error {
	if value == nil {
		ns.AudioFormat, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.AudioFormat.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullAudioFormat) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.AudioFormat), nil
}

func (e AudioFormat) Valid() bool {
	switch e {
	case AudioFormatMp3,
		AudioFormatWav:
		return true
	}
	return false
}

func AllAudioFormatValues() []AudioFormat {
	return []AudioFormat{
		AudioFormatMp3,
		AudioFormatWav,
	}
}

type MediaFormat string

const (
	MediaFormatMp4 MediaFormat = "mp4"
	MediaFormatMp3 MediaFormat = "mp3"
	MediaFormatWav MediaFormat = "wav"
)

func (e *MediaFormat) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = MediaFormat(s)
	case string:
		*e = MediaFormat(s)
	default:
		return fmt.Errorf("unsupported scan type for MediaFormat: %T", src)
	}
	return nil
}

type NullMediaFormat struct {
	MediaFormat MediaFormat
	Valid       bool // Valid is true if MediaFormat is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullMediaFormat) Scan(value interface{}) error {
	if value == nil {
		ns.MediaFormat, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.MediaFormat.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullMediaFormat) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.MediaFormat), nil
}

func (e MediaFormat) Valid() bool {
	switch e {
	case MediaFormatMp4,
		MediaFormatMp3,
		MediaFormatWav:
		return true
	}
	return false
}

func AllMediaFormatValues() []MediaFormat {
	return []MediaFormat{
		MediaFormatMp4,
		MediaFormatMp3,
		MediaFormatWav,
	}
}

type RequestKind string

const (
	RequestKindFile   RequestKind = "file"
	RequestKindStream RequestKind = "stream"
	RequestKindTask   RequestKind = "task"
)

func (e *RequestKind) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = RequestKind(s)
	case string:
		*e = RequestKind(s)
	default:
		return fmt.Errorf("unsupported scan type for RequestKind: %T", src)
	}
	return nil
}

type NullRequestKind struct {
	RequestKind RequestKind
	Valid       bool // Valid is true if RequestKind is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullRequestKind) Scan(value interface{}) error {
	if value == nil {
		ns.RequestKind, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.RequestKind.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullRequestKind) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.RequestKind), nil
}

func (e RequestKind) Valid() bool {
	switch e {
	case RequestKindFile,
		RequestKindStream,
		RequestKindTask:
		return true
	}
	return false
}

func AllRequestKindValues() []RequestKind {
	return []RequestKind{
		RequestKindFile,
		RequestKindStream,
		RequestKindTask,
	}
}

type RequestStatus string

const (
	RequestStatusPending RequestStatus = "pending"
	RequestStatusOk      RequestStatus = "ok"
	RequestStatusError   RequestStatus = "error"
)

func (e *RequestStatus) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = RequestStatus(s)
	case string:
		*e = RequestStatus(s)
	default:
		return fmt.Errorf("unsupported scan type for RequestStatus: %T", src)
	}
	return nil
}

type NullRequestStatus struct {
	RequestStatus RequestStatus
	Valid         bool // Valid is true if RequestStatus is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullRequestStatus) Scan(value interface{}) error {
	if value == nil {
		ns.RequestStatus, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.RequestStatus.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullRequestStatus) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.RequestStatus), nil
}

func (e RequestStatus) Valid() bool {
	switch e {
	case RequestStatusPending,
		RequestStatusOk,
		RequestStatusError:
		return true
	}
	return false
}

func AllRequestStatusValues() []RequestStatus {
	return []RequestStatus{
		RequestStatusPending,
		RequestStatusOk,
		RequestStatusError,
	}
}

type TaskStatus string

const (
	TaskStatusQueued    TaskStatus = "queued"
	TaskStatusRunning   TaskStatus = "running"
	TaskStatusSucceeded TaskStatus = "succeeded"
	TaskStatusFailed    TaskStatus = "failed"
)

func (e *TaskStatus) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = TaskStatus(s)
	case string:
		*e = TaskStatus(s)
	default:
		return fmt.Errorf("unsupported scan type for TaskStatus: %T", src)
	}
	return nil
}

type NullTaskStatus struct {
	TaskStatus TaskStatus
	Valid      bool // Valid is true if TaskStatus is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullTaskStatus) Scan(value interface{}) error {
	if value == nil {
		ns.TaskStatus, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.TaskStatus.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullTaskStatus) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.TaskStatus), nil
}

func (e TaskStatus) Valid() bool {
	switch e {
	case TaskStatusQueued,
		TaskStatusRunning,
		TaskStatusSucceeded,
		TaskStatusFailed:
		return true
	}
	return false
}

func AllTaskStatusValues() []TaskStatus {
	return []TaskStatus{
		TaskStatusQueued,
		TaskStatusRunning,
		TaskStatusSucceeded,
		TaskStatusFailed,
	}
}

type UserRole string

const (
	UserRoleUser  UserRole = "user"
	UserRoleAdmin UserRole = "admin"
)

func (e *UserRole) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = UserRole(s)
	case string:
		*e = UserRole(s)
	default:
		return fmt.Errorf("unsupported scan type for UserRole: %T", src)
	}
	return nil
}

type NullUserRole struct {
	UserRole UserRole
	Valid    bool // Valid is true if UserRole is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullUserRole) Scan(value interface{}) error {
	if value == nil {
		ns.UserRole, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.UserRole.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullUserRole) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.UserRole), nil
}

func (e UserRole) Valid() bool {
	switch e {
	case UserRoleUser,
		UserRoleAdmin:
		return true
	}
	return false
}

func AllUserRoleValues() []UserRole {
	return []UserRole{
		UserRoleUser,
		UserRoleAdmin,
	}
}

type WebhookState string

const (
	WebhookStateNone      WebhookState = "none"
	WebhookStatePending   WebhookState = "pending"
	WebhookStateDelivered WebhookState = "delivered"
	WebhookStateFailed    WebhookState = "failed"
)

func (e *WebhookState) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = WebhookState(s)
	case string:
		*e = WebhookState(s)
	default:
		return fmt.Errorf("unsupported scan type for WebhookState: %T", src)
	}
	return nil
}

type NullWebhookState struct {
	WebhookState WebhookState
	Valid        bool // Valid is true if WebhookState is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullWebhookState) Scan(value interface{}) error {
	if value == nil {
		ns.WebhookState, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.WebhookState.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullWebhookState) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.WebhookState), nil
}

func (e WebhookState) Valid() bool {
	switch e {
	case WebhookStateNone,
		WebhookStatePending,
		WebhookStateDelivered,
		WebhookStateFailed:
		return true
	}
	return false
}

func AllWebhookStateValues() []WebhookState {
	return []WebhookState{
		WebhookStateNone,
		WebhookStatePending,
		WebhookStateDelivered,
		WebhookStateFailed,
	}
}

type ApiKey struct {
	ID         int64
	UserID     int64
	KeyHash    []byte
	Prefix     string
	Name       string
	CreatedAt  time.Time
	LastUsedAt *time.Time
	RevokedAt  *time.Time
}

type Audio struct {
	ID              int64
	SourceID        string
	Format          AudioFormat
	Url             string
	Title           string
	DurationSeconds *int32
	StorageKey      *string
	LastUploadedAt  time.Time
	CreatedAt       time.Time
	LastRequestedAt time.Time
}

type RequestHistory struct {
	ID         int64
	UserID     int64
	ApiKeyID   *int64
	Kind       RequestKind
	Query      string
	SourceUrl  string
	Format     MediaFormat
	SourceID   *string
	Title      string
	Status     RequestStatus
	HttpStatus *int32
	FromCache  bool
	TaskID     *uuid.UUID
	Error      *string
	DurationMs *int64
	CreatedAt  time.Time
}

type Task struct {
	ID              uuid.UUID
	UserID          int64
	ApiKeyID        *int64
	IdempotencyKey  *string
	RequestHash     []byte
	Query           string
	SourceUrl       string
	Format          MediaFormat
	SourceID        *string
	Title           string
	StorageKey      *string
	Status          TaskStatus
	Error           *string
	Attempts        int32
	LockedUntil     *time.Time
	WebhookUrl      *string
	WebhookState    WebhookState
	WebhookAttempts int32
	NextWebhookAt   *time.Time
	WebhookError    *string
	HistoryID       *int64
	CreatedAt       time.Time
	StartedAt       *time.Time
	CompletedAt     *time.Time
	ExpiresAt       *time.Time
}

type User struct {
	ID            int64
	Username      string
	Email         string
	Role          UserRole
	RegisteredAt  time.Time
	WebhookSecret string
}

type Video struct {
	ID              int64
	SourceID        string
	Url             string
	Title           string
	DurationSeconds *int32
	StorageKey      *string
	LastUploadedAt  time.Time
	CreatedAt       time.Time
	LastRequestedAt time.Time
}
