// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package dbgen

import (
	"database/sql/driver"
	"fmt"
	"time"
)

type AudioFormat string

const (
	AudioFormatMp3 AudioFormat = "mp3"
	AudioFormatWav AudioFormat = "wav"
)

func (e *AudioFormat) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = AudioFormat(s)
	case string:
		*e = AudioFormat(s)
	default:
		return fmt.Errorf("unsupported scan type for AudioFormat: %T", src)
	}
	return nil
}

type NullAudioFormat struct {
	AudioFormat AudioFormat
	Valid       bool // Valid is true if AudioFormat is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullAudioFormat) Scan(value interface{}) error {
	if value == nil {
		ns.AudioFormat, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.AudioFormat.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullAudioFormat) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.AudioFormat), nil
}

func (e AudioFormat) Valid() bool {
	switch e {
	case AudioFormatMp3,
		AudioFormatWav:
		return true
	}
	return false
}

func AllAudioFormatValues() []AudioFormat {
	return []AudioFormat{
		AudioFormatMp3,
		AudioFormatWav,
	}
}

type UserRole string

const (
	UserRoleUser  UserRole = "user"
	UserRoleAdmin UserRole = "admin"
)

func (e *UserRole) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = UserRole(s)
	case string:
		*e = UserRole(s)
	default:
		return fmt.Errorf("unsupported scan type for UserRole: %T", src)
	}
	return nil
}

type NullUserRole struct {
	UserRole UserRole
	Valid    bool // Valid is true if UserRole is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullUserRole) Scan(value interface{}) error {
	if value == nil {
		ns.UserRole, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.UserRole.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullUserRole) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.UserRole), nil
}

func (e UserRole) Valid() bool {
	switch e {
	case UserRoleUser,
		UserRoleAdmin:
		return true
	}
	return false
}

func AllUserRoleValues() []UserRole {
	return []UserRole{
		UserRoleUser,
		UserRoleAdmin,
	}
}

type ApiKey struct {
	ID         int64
	UserID     int64
	KeyHash    []byte
	Prefix     string
	Name       string
	CreatedAt  time.Time
	LastUsedAt *time.Time
	RevokedAt  *time.Time
}

type Audio struct {
	ID              int64
	SourceID        string
	Format          AudioFormat
	Url             string
	Title           string
	DurationSeconds *int32
	StorageKey      *string
	LastUploadedAt  time.Time
	CreatedAt       time.Time
}

type User struct {
	ID           int64
	Username     string
	Email        string
	Role         UserRole
	RegisteredAt time.Time
}

type Video struct {
	ID              int64
	SourceID        string
	Url             string
	Title           string
	DurationSeconds *int32
	StorageKey      *string
	LastUploadedAt  time.Time
	CreatedAt       time.Time
}
