// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package dbgen

import (
	"context"
)

type Querier interface {
	// Marks the file as no longer stored (e.g. evicted); the row is kept.
	ClearAudioStorageKey(ctx context.Context, arg ClearAudioStorageKeyParams) (int64, error)
	// Marks the file as no longer stored (e.g. evicted); the row is kept.
	ClearVideoStorageKey(ctx context.Context, sourceID string) (int64, error)
	CreateAPIKey(ctx context.Context, arg CreateAPIKeyParams) (CreateAPIKeyRow, error)
	CreateUser(ctx context.Context, arg CreateUserParams) (User, error)
	DeleteAudio(ctx context.Context, arg DeleteAudioParams) (int64, error)
	// Cascades to the user's API keys.
	DeleteUser(ctx context.Context, id int64) (int64, error)
	DeleteVideo(ctx context.Context, sourceID string) (int64, error)
	GetAudio(ctx context.Context, arg GetAudioParams) (Audio, error)
	// Resolves an active (not revoked) key to its owner.
	GetUserByAPIKeyHash(ctx context.Context, keyHash []byte) (GetUserByAPIKeyHashRow, error)
	GetUserByEmail(ctx context.Context, email string) (User, error)
	GetUserByID(ctx context.Context, id int64) (User, error)
	GetVideoBySourceID(ctx context.Context, sourceID string) (Video, error)
	// Never returns key_hash.
	ListAPIKeysByUser(ctx context.Context, userID int64) ([]ListAPIKeysByUserRow, error)
	ListAudio(ctx context.Context, arg ListAudioParams) ([]Audio, error)
	ListUsers(ctx context.Context, arg ListUsersParams) ([]User, error)
	ListVideos(ctx context.Context, arg ListVideosParams) ([]Video, error)
	// Scoped by user_id so one user cannot revoke another user's key.
	RevokeAPIKey(ctx context.Context, arg RevokeAPIKeyParams) (int64, error)
	TouchAPIKey(ctx context.Context, id int64) error
	UpdateUserRole(ctx context.Context, arg UpdateUserRoleParams) (User, error)
	// Records an upload to storage; a repeat upload of the same video in the same
	// format refreshes the row and its last_uploaded_at.
	UpsertAudio(ctx context.Context, arg UpsertAudioParams) (Audio, error)
	// Records an upload to storage; a repeat upload of the same video refreshes
	// the row and its last_uploaded_at.
	UpsertVideo(ctx context.Context, arg UpsertVideoParams) (Video, error)
}

var _ Querier = (*Queries)(nil)
