// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: tasks.sql

package dbgen

import (
	"context"

	"github.com/google/uuid"
)

const claimTask = `-- name: ClaimTask :one
UPDATE tasks
SET status       = 'running',
    started_at   = coalesce(started_at, now()),
    locked_until = now() + make_interval(secs => $1::float8),
    attempts     = attempts + 1
WHERE id = (
    SELECT id FROM tasks
    WHERE (status = 'queued' OR (status = 'running' AND locked_until < now()))
      AND attempts < $2::integer
    ORDER BY created_at
    FOR UPDATE SKIP LOCKED
    LIMIT 1)
RETURNING id, user_id, api_key_id, idempotency_key, request_hash, query, source_url, format, source_id, title, storage_key, status, error, attempts, locked_until, webhook_url, webhook_state, webhook_attempts, next_webhook_at, webhook_error, history_id, created_at, started_at, completed_at, expires_at, quality
`

type ClaimTaskParams struct {
	LeaseSeconds float64
	MaxAttempts  int32
}

// Takes the oldest queued task, or a running one whose worker lease expired
// (the worker died). SKIP LOCKED lets any number of workers and instances
// poll concurrently without handing out the same task twice.
func (q *Queries) ClaimTask(ctx context.Context, arg ClaimTaskParams) (Task, error) {
	row := q.db.QueryRow(ctx, claimTask, arg.LeaseSeconds, arg.MaxAttempts)
	var i Task
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.ApiKeyID,
		&i.IdempotencyKey,
		&i.RequestHash,
		&i.Query,
		&i.SourceUrl,
		&i.Format,
		&i.SourceID,
		&i.Title,
		&i.StorageKey,
		&i.Status,
		&i.Error,
		&i.Attempts,
		&i.LockedUntil,
		&i.WebhookUrl,
		&i.WebhookState,
		&i.WebhookAttempts,
		&i.NextWebhookAt,
		&i.WebhookError,
		&i.HistoryID,
		&i.CreatedAt,
		&i.StartedAt,
		&i.CompletedAt,
		&i.ExpiresAt,
		&i.Quality,
	)
	return i, err
}

const claimWebhook = `-- name: ClaimWebhook :one
UPDATE tasks
SET next_webhook_at  = now() + make_interval(secs => $1::float8),
    webhook_attempts = webhook_attempts + 1
WHERE id = (
    SELECT id FROM tasks
    WHERE webhook_state = 'pending' AND next_webhook_at <= now()
    ORDER BY next_webhook_at
    FOR UPDATE SKIP LOCKED
    LIMIT 1)
RETURNING id, user_id, api_key_id, idempotency_key, request_hash, query, source_url, format, source_id, title, storage_key, status, error, attempts, locked_until, webhook_url, webhook_state, webhook_attempts, next_webhook_at, webhook_error, history_id, created_at, started_at, completed_at, expires_at, quality
`

// Pushes next_webhook_at forward as a delivery lease, so another poller does
// not pick the same webhook while this delivery is in progress.
func (q *Queries) ClaimWebhook(ctx context.Context, leaseSeconds float64) (Task, error) {
	row := q.db.QueryRow(ctx, claimWebhook, leaseSeconds)
	var i Task
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.ApiKeyID,
		&i.IdempotencyKey,
		&i.RequestHash,
		&i.Query,
		&i.SourceUrl,
		&i.Format,
		&i.SourceID,
		&i.Title,
		&i.StorageKey,
		&i.Status,
		&i.Error,
		&i.Attempts,
		&i.LockedUntil,
		&i.WebhookUrl,
		&i.WebhookState,
		&i.WebhookAttempts,
		&i.NextWebhookAt,
		&i.WebhookError,
		&i.HistoryID,
		&i.CreatedAt,
		&i.StartedAt,
		&i.CompletedAt,
		&i.ExpiresAt,
		&i.Quality,
	)
	return i, err
}

const completeTask = `-- name: CompleteTask :one
UPDATE tasks
SET status          = 'succeeded',
    source_id       = $2,
    title           = $3,
    storage_key     = $4,
    error           = NULL,
    completed_at    = now(),
    expires_at      = now() + make_interval(secs => $5::float8),
    locked_until    = NULL,
    webhook_state   = CASE WHEN webhook_url IS NOT NULL THEN 'pending'::webhook_state ELSE 'none'::webhook_state END,
    next_webhook_at = now()
WHERE id = $1
RETURNING id, user_id, api_key_id, idempotency_key, request_hash, query, source_url, format, source_id, title, storage_key, status, error, attempts, locked_until, webhook_url, webhook_state, webhook_attempts, next_webhook_at, webhook_error, history_id, created_at, started_at, completed_at, expires_at, quality
`

type CompleteTaskParams struct {
	ID               uuid.UUID
	SourceID         *string
	Title            string
	StorageKey       *string
	ResultTtlSeconds float64
}

func (q *Queries) CompleteTask(ctx context.Context, arg CompleteTaskParams) (Task, error) {
	row := q.db.QueryRow(ctx, completeTask,
		arg.ID,
		arg.SourceID,
		arg.Title,
		arg.StorageKey,
		arg.ResultTtlSeconds,
	)
	var i Task
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.ApiKeyID,
		&i.IdempotencyKey,
		&i.RequestHash,
		&i.Query,
		&i.SourceUrl,
		&i.Format,
		&i.SourceID,
		&i.Title,
		&i.StorageKey,
		&i.Status,
		&i.Error,
		&i.Attempts,
		&i.LockedUntil,
		&i.WebhookUrl,
		&i.WebhookState,
		&i.WebhookAttempts,
		&i.NextWebhookAt,
		&i.WebhookError,
		&i.HistoryID,
		&i.CreatedAt,
		&i.StartedAt,
		&i.CompletedAt,
		&i.ExpiresAt,
		&i.Quality,
	)
	return i, err
}

const createTask = `-- name: CreateTask :one
INSERT INTO tasks (user_id, api_key_id, idempotency_key, request_hash, query, source_url, format, quality, webhook_url)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9)
ON CONFLICT (user_id, idempotency_key) DO NOTHING
RETURNING id, user_id, api_key_id, idempotency_key, request_hash, query, source_url, format, source_id, title, storage_key, status, error, attempts, locked_until, webhook_url, webhook_state, webhook_attempts, next_webhook_at, webhook_error, history_id, created_at, started_at, completed_at, expires_at, quality
`

type CreateTaskParams struct {
	UserID         int64
	ApiKeyID       *int64
	IdempotencyKey *string
	RequestHash    []byte
	Query          string
	SourceUrl      string
	Format         MediaFormat
	Quality        VideoQuality
	WebhookUrl     *string
}

// Returns no row when (user_id, idempotency_key) already exists; the caller
// then loads the existing task with GetTaskByIdempotency.
func (q *Queries) CreateTask(ctx context.Context, arg CreateTaskParams) (Task, error) {
	row := q.db.QueryRow(ctx, createTask,
		arg.UserID,
		arg.ApiKeyID,
		arg.IdempotencyKey,
		arg.RequestHash,
		arg.Query,
		arg.SourceUrl,
		arg.Format,
		arg.Quality,
		arg.WebhookUrl,
	)
	var i Task
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.ApiKeyID,
		&i.IdempotencyKey,
		&i.RequestHash,
		&i.Query,
		&i.SourceUrl,
		&i.Format,
		&i.SourceID,
		&i.Title,
		&i.StorageKey,
		&i.Status,
		&i.Error,
		&i.Attempts,
		&i.LockedUntil,
		&i.WebhookUrl,
		&i.WebhookState,
		&i.WebhookAttempts,
		&i.NextWebhookAt,
		&i.WebhookError,
		&i.HistoryID,
		&i.CreatedAt,
		&i.StartedAt,
		&i.CompletedAt,
		&i.ExpiresAt,
		&i.Quality,
	)
	return i, err
}

const extendTaskLease = `-- name: ExtendTaskLease :execrows
UPDATE tasks SET locked_until = now() + make_interval(secs => $2::float8)
WHERE id = $1 AND status = 'running'
`

type ExtendTaskLeaseParams struct {
	ID           uuid.UUID
	LeaseSeconds float64
}

func (q *Queries) ExtendTaskLease(ctx context.Context, arg ExtendTaskLeaseParams) (int64, error) {
	result, err := q.db.Exec(ctx, extendTaskLease, arg.ID, arg.LeaseSeconds)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const failAbandonedTasks = `-- name: FailAbandonedTasks :execrows
UPDATE tasks
SET status        = 'failed',
    error         = 'worker lost the task too many times',
    completed_at  = now(),
    locked_until  = NULL,
    webhook_state = CASE WHEN webhook_url IS NOT NULL THEN 'pending'::webhook_state ELSE 'none'::webhook_state END,
    next_webhook_at = now()
WHERE status = 'running' AND locked_until < now() AND attempts >= $1::integer
`

// Tasks whose worker died on the last allowed attempt would otherwise stay
// "running" forever.
func (q *Queries) FailAbandonedTasks(ctx context.Context, maxAttempts int32) (int64, error) {
	result, err := q.db.Exec(ctx, failAbandonedTasks, maxAttempts)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const failTask = `-- name: FailTask :one
UPDATE tasks
SET status          = 'failed',
    error           = $2,
    completed_at    = now(),
    locked_until    = NULL,
    webhook_state   = CASE WHEN webhook_url IS NOT NULL THEN 'pending'::webhook_state ELSE 'none'::webhook_state END,
    next_webhook_at = now()
WHERE id = $1
RETURNING id, user_id, api_key_id, idempotency_key, request_hash, query, source_url, format, source_id, title, storage_key, status, error, attempts, locked_until, webhook_url, webhook_state, webhook_attempts, next_webhook_at, webhook_error, history_id, created_at, started_at, completed_at, expires_at, quality
`

type FailTaskParams struct {
	ID    uuid.UUID
	Error *string
}

func (q *Queries) FailTask(ctx context.Context, arg FailTaskParams) (Task, error) {
	row := q.db.QueryRow(ctx, failTask, arg.ID, arg.Error)
	var i Task
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.ApiKeyID,
		&i.IdempotencyKey,
		&i.RequestHash,
		&i.Query,
		&i.SourceUrl,
		&i.Format,
		&i.SourceID,
		&i.Title,
		&i.StorageKey,
		&i.Status,
		&i.Error,
		&i.Attempts,
		&i.LockedUntil,
		&i.WebhookUrl,
		&i.WebhookState,
		&i.WebhookAttempts,
		&i.NextWebhookAt,
		&i.WebhookError,
		&i.HistoryID,
		&i.CreatedAt,
		&i.StartedAt,
		&i.CompletedAt,
		&i.ExpiresAt,
		&i.Quality,
	)
	return i, err
}

const findReusableTask = `-- name: FindReusableTask :one
SELECT id, user_id, api_key_id, idempotency_key, request_hash, query, source_url, format, source_id, title, storage_key, status, error, attempts, locked_until, webhook_url, webhook_state, webhook_attempts, next_webhook_at, webhook_error, history_id, created_at, started_at, completed_at, expires_at, quality FROM tasks
WHERE user_id = $1 AND request_hash = $2
  AND (status IN ('queued', 'running') OR (status = 'succeeded' AND expires_at > now()))
ORDER BY created_at DESC
LIMIT 1
`

type FindReusableTaskParams struct {
	UserID      int64
	RequestHash []byte
}

// Implicit idempotency: the newest identical request that is still in flight
// or whose result is still downloadable.
func (q *Queries) FindReusableTask(ctx context.Context, arg FindReusableTaskParams) (Task, error) {
	row := q.db.QueryRow(ctx, findReusableTask, arg.UserID, arg.RequestHash)
	var i Task
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.ApiKeyID,
		&i.IdempotencyKey,
		&i.RequestHash,
		&i.Query,
		&i.SourceUrl,
		&i.Format,
		&i.SourceID,
		&i.Title,
		&i.StorageKey,
		&i.Status,
		&i.Error,
		&i.Attempts,
		&i.LockedUntil,
		&i.WebhookUrl,
		&i.WebhookState,
		&i.WebhookAttempts,
		&i.NextWebhookAt,
		&i.WebhookError,
		&i.HistoryID,
		&i.CreatedAt,
		&i.StartedAt,
		&i.CompletedAt,
		&i.ExpiresAt,
		&i.Quality,
	)
	return i, err
}

const getTask = `-- name: GetTask :one
SELECT id, user_id, api_key_id, idempotency_key, request_hash, query, source_url, format, source_id, title, storage_key, status, error, attempts, locked_until, webhook_url, webhook_state, webhook_attempts, next_webhook_at, webhook_error, history_id, created_at, started_at, completed_at, expires_at, quality FROM tasks WHERE id = $1
`

func (q *Queries) GetTask(ctx context.Context, id uuid.UUID) (Task, error) {
	row := q.db.QueryRow(ctx, getTask, id)
	var i Task
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.ApiKeyID,
		&i.IdempotencyKey,
		&i.RequestHash,
		&i.Query,
		&i.SourceUrl,
		&i.Format,
		&i.SourceID,
		&i.Title,
		&i.StorageKey,
		&i.Status,
		&i.Error,
		&i.Attempts,
		&i.LockedUntil,
		&i.WebhookUrl,
		&i.WebhookState,
		&i.WebhookAttempts,
		&i.NextWebhookAt,
		&i.WebhookError,
		&i.HistoryID,
		&i.CreatedAt,
		&i.StartedAt,
		&i.CompletedAt,
		&i.ExpiresAt,
		&i.Quality,
	)
	return i, err
}

const getTaskByIdempotency = `-- name: GetTaskByIdempotency :one
SELECT id, user_id, api_key_id, idempotency_key, request_hash, query, source_url, format, source_id, title, storage_key, status, error, attempts, locked_until, webhook_url, webhook_state, webhook_attempts, next_webhook_at, webhook_error, history_id, created_at, started_at, completed_at, expires_at, quality FROM tasks WHERE user_id = $1 AND idempotency_key = $2
`

type GetTaskByIdempotencyParams struct {
	UserID         int64
	IdempotencyKey *string
}

func (q *Queries) GetTaskByIdempotency(ctx context.Context, arg GetTaskByIdempotencyParams) (Task, error) {
	row := q.db.QueryRow(ctx, getTaskByIdempotency, arg.UserID, arg.IdempotencyKey)
	var i Task
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.ApiKeyID,
		&i.IdempotencyKey,
		&i.RequestHash,
		&i.Query,
		&i.SourceUrl,
		&i.Format,
		&i.SourceID,
		&i.Title,
		&i.StorageKey,
		&i.Status,
		&i.Error,
		&i.Attempts,
		&i.LockedUntil,
		&i.WebhookUrl,
		&i.WebhookState,
		&i.WebhookAttempts,
		&i.NextWebhookAt,
		&i.WebhookError,
		&i.HistoryID,
		&i.CreatedAt,
		&i.StartedAt,
		&i.CompletedAt,
		&i.ExpiresAt,
		&i.Quality,
	)
	return i, err
}

const markWebhookDelivered = `-- name: MarkWebhookDelivered :exec
UPDATE tasks SET webhook_state = 'delivered', webhook_error = NULL, next_webhook_at = NULL WHERE id = $1
`

func (q *Queries) MarkWebhookDelivered(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.Exec(ctx, markWebhookDelivered, id)
	return err
}

const markWebhookFailed = `-- name: MarkWebhookFailed :exec
UPDATE tasks SET webhook_state = 'failed', webhook_error = $2, next_webhook_at = NULL WHERE id = $1
`

type MarkWebhookFailedParams struct {
	ID           uuid.UUID
	WebhookError *string
}

func (q *Queries) MarkWebhookFailed(ctx context.Context, arg MarkWebhookFailedParams) error {
	_, err := q.db.Exec(ctx, markWebhookFailed, arg.ID, arg.WebhookError)
	return err
}

const markWebhookRetry = `-- name: MarkWebhookRetry :exec
UPDATE tasks
SET webhook_error   = $2,
    next_webhook_at = now() + make_interval(secs => $3::float8)
WHERE id = $1
`

type MarkWebhookRetryParams struct {
	ID           uuid.UUID
	WebhookError *string
	DelaySeconds float64
}

func (q *Queries) MarkWebhookRetry(ctx context.Context, arg MarkWebhookRetryParams) error {
	_, err := q.db.Exec(ctx, markWebhookRetry, arg.ID, arg.WebhookError, arg.DelaySeconds)
	return err
}

const setTaskHistory = `-- name: SetTaskHistory :exec
UPDATE tasks SET history_id = $2 WHERE id = $1
`

type SetTaskHistoryParams struct {
	ID        uuid.UUID
	HistoryID *int64
}

func (q *Queries) SetTaskHistory(ctx context.Context, arg SetTaskHistoryParams) error {
	_, err := q.db.Exec(ctx, setTaskHistory, arg.ID, arg.HistoryID)
	return err
}
