// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: users.sql

package dbgen

import (
	"context"
)

const countUsers = `-- name: CountUsers :one
SELECT count(*) FROM users
`

func (q *Queries) CountUsers(ctx context.Context) (int64, error) {
	row := q.db.QueryRow(ctx, countUsers)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createUser = `-- name: CreateUser :one
INSERT INTO users (username, email, role)
VALUES ($1, $2, $3)
RETURNING id, username, email, role, registered_at, webhook_secret
`

type CreateUserParams struct {
	Username string
	Email    string
	Role     UserRole
}

func (q *Queries) CreateUser(ctx context.Context, arg CreateUserParams) (User, error) {
	row := q.db.QueryRow(ctx, createUser, arg.Username, arg.Email, arg.Role)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Username,
		&i.Email,
		&i.Role,
		&i.RegisteredAt,
		&i.WebhookSecret,
	)
	return i, err
}

const deleteUser = `-- name: DeleteUser :execrows
DELETE FROM users WHERE id = $1
`

// Cascades to the user's API keys.
func (q *Queries) DeleteUser(ctx context.Context, id int64) (int64, error) {
	result, err := q.db.Exec(ctx, deleteUser, id)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const getUserByEmail = `-- name: GetUserByEmail :one
SELECT id, username, email, role, registered_at, webhook_secret FROM users WHERE lower(email) = lower($1)
`

func (q *Queries) GetUserByEmail(ctx context.Context, email string) (User, error) {
	row := q.db.QueryRow(ctx, getUserByEmail, email)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Username,
		&i.Email,
		&i.Role,
		&i.RegisteredAt,
		&i.WebhookSecret,
	)
	return i, err
}

const getUserByID = `-- name: GetUserByID :one
SELECT id, username, email, role, registered_at, webhook_secret FROM users WHERE id = $1
`

func (q *Queries) GetUserByID(ctx context.Context, id int64) (User, error) {
	row := q.db.QueryRow(ctx, getUserByID, id)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Username,
		&i.Email,
		&i.Role,
		&i.RegisteredAt,
		&i.WebhookSecret,
	)
	return i, err
}

const listUsers = `-- name: ListUsers :many
SELECT id, username, email, role, registered_at, webhook_secret FROM users
ORDER BY id
LIMIT $1 OFFSET $2
`

type ListUsersParams struct {
	Limit  int32
	Offset int32
}

func (q *Queries) ListUsers(ctx context.Context, arg ListUsersParams) ([]User, error) {
	rows, err := q.db.Query(ctx, listUsers, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []User
	for rows.Next() {
		var i User
		if err := rows.Scan(
			&i.ID,
			&i.Username,
			&i.Email,
			&i.Role,
			&i.RegisteredAt,
			&i.WebhookSecret,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const setWebhookSecret = `-- name: SetWebhookSecret :one
UPDATE users SET webhook_secret = $2 WHERE id = $1
RETURNING webhook_secret
`

type SetWebhookSecretParams struct {
	ID            int64
	WebhookSecret string
}

func (q *Queries) SetWebhookSecret(ctx context.Context, arg SetWebhookSecretParams) (string, error) {
	row := q.db.QueryRow(ctx, setWebhookSecret, arg.ID, arg.WebhookSecret)
	var webhook_secret string
	err := row.Scan(&webhook_secret)
	return webhook_secret, err
}

const updateUser = `-- name: UpdateUser :one
UPDATE users
SET username = coalesce($1, username),
    email    = coalesce($2, email),
    role     = coalesce($3, role)
WHERE id = $4
RETURNING id, username, email, role, registered_at, webhook_secret
`

type UpdateUserParams struct {
	Username *string
	Email    *string
	Role     NullUserRole
	ID       int64
}

// Partial update: NULL arguments keep the current value.
func (q *Queries) UpdateUser(ctx context.Context, arg UpdateUserParams) (User, error) {
	row := q.db.QueryRow(ctx, updateUser,
		arg.Username,
		arg.Email,
		arg.Role,
		arg.ID,
	)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Username,
		&i.Email,
		&i.Role,
		&i.RegisteredAt,
		&i.WebhookSecret,
	)
	return i, err
}

const updateUserRole = `-- name: UpdateUserRole :one
UPDATE users SET role = $2 WHERE id = $1
RETURNING id, username, email, role, registered_at, webhook_secret
`

type UpdateUserRoleParams struct {
	ID   int64
	Role UserRole
}

func (q *Queries) UpdateUserRole(ctx context.Context, arg UpdateUserRoleParams) (User, error) {
	row := q.db.QueryRow(ctx, updateUserRole, arg.ID, arg.Role)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Username,
		&i.Email,
		&i.Role,
		&i.RegisteredAt,
		&i.WebhookSecret,
	)
	return i, err
}
