// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: videos.sql

package dbgen

import (
	"context"
)

const clearVideoStorageKey = `-- name: ClearVideoStorageKey :execrows
UPDATE videos SET storage_key = NULL WHERE source_id = $1
`

// Marks the file as no longer stored (e.g. evicted); the row is kept.
func (q *Queries) ClearVideoStorageKey(ctx context.Context, sourceID string) (int64, error) {
	result, err := q.db.Exec(ctx, clearVideoStorageKey, sourceID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const deleteVideo = `-- name: DeleteVideo :execrows
DELETE FROM videos WHERE source_id = $1
`

func (q *Queries) DeleteVideo(ctx context.Context, sourceID string) (int64, error) {
	result, err := q.db.Exec(ctx, deleteVideo, sourceID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const getVideoBySourceID = `-- name: GetVideoBySourceID :one
SELECT id, source_id, url, title, duration_seconds, storage_key, last_uploaded_at, created_at FROM videos WHERE source_id = $1
`

func (q *Queries) GetVideoBySourceID(ctx context.Context, sourceID string) (Video, error) {
	row := q.db.QueryRow(ctx, getVideoBySourceID, sourceID)
	var i Video
	err := row.Scan(
		&i.ID,
		&i.SourceID,
		&i.Url,
		&i.Title,
		&i.DurationSeconds,
		&i.StorageKey,
		&i.LastUploadedAt,
		&i.CreatedAt,
	)
	return i, err
}

const listVideos = `-- name: ListVideos :many
SELECT id, source_id, url, title, duration_seconds, storage_key, last_uploaded_at, created_at FROM videos
ORDER BY last_uploaded_at DESC, id DESC
LIMIT $1 OFFSET $2
`

type ListVideosParams struct {
	Limit  int32
	Offset int32
}

func (q *Queries) ListVideos(ctx context.Context, arg ListVideosParams) ([]Video, error) {
	rows, err := q.db.Query(ctx, listVideos, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Video
	for rows.Next() {
		var i Video
		if err := rows.Scan(
			&i.ID,
			&i.SourceID,
			&i.Url,
			&i.Title,
			&i.DurationSeconds,
			&i.StorageKey,
			&i.LastUploadedAt,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const upsertVideo = `-- name: UpsertVideo :one
INSERT INTO videos (source_id, url, title, duration_seconds, storage_key)
VALUES ($1, $2, $3, $4, $5)
ON CONFLICT (source_id) DO UPDATE
SET url              = EXCLUDED.url,
    title            = EXCLUDED.title,
    duration_seconds = EXCLUDED.duration_seconds,
    storage_key      = EXCLUDED.storage_key,
    last_uploaded_at = now()
RETURNING id, source_id, url, title, duration_seconds, storage_key, last_uploaded_at, created_at
`

type UpsertVideoParams struct {
	SourceID        string
	Url             string
	Title           string
	DurationSeconds *int32
	StorageKey      *string
}

// Records an upload to storage; a repeat upload of the same video refreshes
// the row and its last_uploaded_at.
func (q *Queries) UpsertVideo(ctx context.Context, arg UpsertVideoParams) (Video, error) {
	row := q.db.QueryRow(ctx, upsertVideo,
		arg.SourceID,
		arg.Url,
		arg.Title,
		arg.DurationSeconds,
		arg.StorageKey,
	)
	var i Video
	err := row.Scan(
		&i.ID,
		&i.SourceID,
		&i.Url,
		&i.Title,
		&i.DurationSeconds,
		&i.StorageKey,
		&i.LastUploadedAt,
		&i.CreatedAt,
	)
	return i, err
}
